use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# TestlySmartProxyWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :testly_smart_proxy_web, TestlySmartProxyWeb.Endpoint,
  load_from_system_env: false,
  http: [port: 4003, compress: true],
  secret_key_base: "CB2ZRDdtsxUa6EwJFFJN87iVb//i+337avsVlNx/7wy+HOORuarcL8Lb+G9zCVhj",
  url: [host: "example.com", port: 80],
  server: true
